# Generated by Django 4.1.2 on 2022-11-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe_sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('avail', models.BooleanField(default=True)),
                ('size', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('article', models.CharField(default='1', max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.colors')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.countries')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.genders')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cat_types')),
            ],
        ),
        migrations.AddField(
            model_name='cat_types',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categories'),
        ),
    ]
